travis:
  secure:
    BINSTAR_TOKEN: L/y0JjFlIlv7j3b82gp/Tpfpk8+ajigADUFMgHMPaz9xYmhOXFtHijoTXdzcEqQTsKlJUpF3O3BDKbzVOPZBsQArq+tFAcMeXrvDAOnEUtOl/9iwZj/YdRqaEQcomh1mFxJ1gNMKRGZ9ciirOsTg5vDgezg5K5O220QZUiDp9yRVInpgWSDWjWMjmHoh7s2KmtxPKjLTWqlshYOQUtrAwYYTRMZRoPz0v1ewDpSIHIzo+C0t3g9nRzg2jNvE6vpmOWQ70gL3nY97EH3uNp1mvNdmKQ719XeL06vjvPQfCF0vcl0iDrjRNkukQFjCLL2dwpYI69xOx0X8KRQ7ImEeEkmtVAqRLOMZbfhEwwu71DxOMFqJHI+gB9t3bVgRMNC+T/Gxu/i1r2RUMBHNaE0tqBOa/oqT013BvjsKP2XtTtYsRb/RyxlK2YKpX5LafHph/fNsVX+FNSOUIvQNPtY4Rzw04+/i8QX155r8oAVSB4M4blPpjl9mSUER5pXHpprWbdHNEOu5yLXLhEsJZFRIWVjgkFl+0vdUHWbnEOe+/2o0IBdEN0NfMG8Won28MluTH9XRCdnvsTW0nrQzvQUST61utr0HZRcRt/QI3fIE6hRFYzjC31BGOEuUFOkgeuBZsgyRSi6n90pEva3/28T2QCIDvt+ZY2qYd3qF2U2FpQY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
